default: &default
  adapter: cockroachdb
  host: <%= Rails.application.credentials.dig(:cockroachdb, :host) %>
  port: 26257
  user: <%= Rails.application.credentials.dig(:cockroachdb, :user) %>
  password: <%= Rails.application.credentials.dig(:cockroachdb, :password) %>
  database: <%= Rails.application.credentials.dig(:cockroachdb, :database) %>
  sslmode: "verify-full"
  sslrootcert: "./root.crt"
  options: <%= Rails.application.credentials.dig(:cockroachdb, :option) %>

development:
  <<: *default
  database: social_media_api_development

test:
  <<: *default
  database: social_media_api_test<%= ENV['TEST_ENV_NUMBER'] %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
production:
  <<: *default
